# numpy:

In [1]:
import numpy as np

In [4]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [5]:
arr=np.array([4,6,7])
arr

array([4, 6, 7])

In [6]:
np.array([3,4,5])

array([3, 4, 5])

In [7]:
list_of_lists=([2,4,6],[3,5,7],[1,8,9])
np.array(list_of_lists)

array([[2, 4, 6],
       [3, 5, 7],
       [1, 8, 9]])

In [8]:
np.arange(3,23)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

In [9]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [12]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(8,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.ones((6,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.linspace(0,14,9)

array([ 0.  ,  1.75,  3.5 ,  5.25,  7.  ,  8.75, 10.5 , 12.25, 14.  ])

In [16]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [17]:
np.linspace(3,15,4)

array([ 3.,  7., 11., 15.])

In [18]:
np.eye(7,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [19]:
np.random.rand(3,6)

array([[0.86670287, 0.82998689, 0.78301196, 0.65148405, 0.25814135,
        0.63854819],
       [0.07503708, 0.62236465, 0.17640766, 0.66461803, 0.56588375,
        0.3456156 ],
       [0.27549651, 0.30817371, 0.83643761, 0.10532914, 0.25672803,
        0.801248  ]])

In [20]:
np.random.randn(3,6)

array([[ 1.17643818, -0.22239781,  0.55393912, -1.14431356,  2.32056265,
        -0.29166014],
       [ 0.49702318,  0.40167979,  0.71028803,  0.10720615, -0.7761992 ,
         1.34620758],
       [-1.51757938,  0.70088475,  2.17358522,  1.56752651, -1.1996329 ,
        -0.7647593 ]])

In [21]:
np.random.randint(0,12,15)

array([11,  7,  3,  4, 10,  1,  6,  9,  8,  5,  6,  2,  1,  1,  9])

In [22]:
np.random.randint(20,50,20)

array([28, 36, 44, 31, 35, 41, 39, 34, 38, 23, 34, 33, 37, 48, 41, 30, 38,
       33, 29, 27])

In [23]:
sample_array=np.arange(4,15)
sample_array

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
rand_array=np.random.randint(0,15,3)
rand_array

array([ 5, 10,  8])

In [25]:
sample_array.min()

4

In [26]:
sample_array.argmin()

0

In [28]:
rand_array.max()

10

In [29]:
rand_array.argmax()

1

In [30]:
sample_array.argmax()

10

In [31]:
sample_array.dtype

dtype('int32')

In [32]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
a=np.random.rand(3,5)
a

array([[0.70398047, 0.04836433, 0.22326933, 0.40694374, 0.04771789],
       [0.1598961 , 0.2711687 , 0.39896096, 0.37108897, 0.81099633],
       [0.67841373, 0.69057583, 0.23653132, 0.19371893, 0.09460277]])

In [35]:
a.T

array([[0.70398047, 0.1598961 , 0.67841373],
       [0.04836433, 0.2711687 , 0.69057583],
       [0.22326933, 0.39896096, 0.23653132],
       [0.40694374, 0.37108897, 0.19371893],
       [0.04771789, 0.81099633, 0.09460277]])

In [36]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [37]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [38]:
sample_array=sample_array.reshape(3,4)

ValueError: cannot reshape array of size 18 into shape (3,4)

In [39]:
sample_array[3]=100
sample_array

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [100, 100, 100],
       [ 22,  23,  24],
       [ 25,  26,  27]])

In [40]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [41]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [42]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [43]:
sample_array[:]=100
sample_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

# two-dimensional array

In [44]:
sample_matrix=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [45]:
sample_matrix[2][2]

24

In [46]:
sample_matrix[1][2]

54

In [47]:
sample_matrix[:,2]

array([ 2, 54, 24])

In [48]:
sample_matrix[1,1]

2

In [51]:
sample_matrix[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [52]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [53]:
sample_matrix[2]

array([56, 76, 24,  7])

In [54]:
sample_array=np.arange(1,30)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [55]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [56]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12])

In [57]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [58]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583])

In [65]:
a=np.array([[1,2,3],[4,5,6]])
a
b=a.ndim
c=a.shape
d=a.size
b,c,d

(2, (2, 3), 6)

In [67]:
f=a.flatten()
f

array([1, 2, 3, 4, 5, 6])

In [68]:
e=a.T
e

array([[1, 4],
       [2, 5],
       [3, 6]])

In [79]:
g=np.expand_dims(a,axis=0)
g

array([[[1, 2, 3],
        [4, 5, 6]]])

### pandas

In [83]:
import pandas as pd

In [84]:
labels=['a','b','c','d']

In [85]:
list=[10,28,3,4]

In [86]:
import numpy as np

In [87]:
array=np.array([1,2,3,4])

In [88]:
dict={'w':10,'x':20,'y':30,'z':40}

In [92]:
pd.Series(data=list)

0    10
1    28
2     3
3     4
dtype: int64

In [94]:
pd.Series(data=list,index=labels)

a    10
b    28
c     3
d     4
dtype: int64

In [95]:
pd.Series(labels,list)

10    a
28    b
3     c
4     d
dtype: object

In [96]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

### pandas dataframe and indexing

In [98]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [99]:
sports1['basketball']

3

In [100]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [101]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [102]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.165853  0.861326  0.749907  0.426012  0.158930
B  0.456251  0.597587  0.540082  0.317487  0.975825
C  0.272142  0.697528  0.620874  0.265688  0.090091
D  0.444873  0.391833  0.248986  0.964221  0.201328
E  0.853847  0.071916  0.487530  0.919425  0.125556
F  0.373855  0.082672  0.615873  0.346279  0.740500
G  0.448209  0.020508  0.313448  0.026528  0.380553
H  0.264285  0.317417  0.897220  0.552093  0.147470

In [103]:
df1[['score1','score2','score3']]

score1    score2    score3
A  0.165853  0.861326  0.749907
B  0.456251  0.597587  0.540082
C  0.272142  0.697528  0.620874
D  0.444873  0.391833  0.248986
E  0.853847  0.071916  0.487530
F  0.373855  0.082672  0.615873
G  0.448209  0.020508  0.313448
H  0.264285  0.317417  0.897220

In [104]:
df1['score6']=df1['score1']-df1['score3']
df1

score1    score2    score3    score4    score5    score6
A  0.165853  0.861326  0.749907  0.426012  0.158930 -0.584055
B  0.456251  0.597587  0.540082  0.317487  0.975825 -0.083831
C  0.272142  0.697528  0.620874  0.265688  0.090091 -0.348732
D  0.444873  0.391833  0.248986  0.964221  0.201328  0.195888
E  0.853847  0.071916  0.487530  0.919425  0.125556  0.366316
F  0.373855  0.082672  0.615873  0.346279  0.740500 -0.242018
G  0.448209  0.020508  0.313448  0.026528  0.380553  0.134761
H  0.264285  0.317417  0.897220  0.552093  0.147470 -0.632936

In [105]:
df1.drop('score4',axis=1)

score1    score2    score3    score5    score6
A  0.165853  0.861326  0.749907  0.158930 -0.584055
B  0.456251  0.597587  0.540082  0.975825 -0.083831
C  0.272142  0.697528  0.620874  0.090091 -0.348732
D  0.444873  0.391833  0.248986  0.201328  0.195888
E  0.853847  0.071916  0.487530  0.125556  0.366316
F  0.373855  0.082672  0.615873  0.740500 -0.242018
G  0.448209  0.020508  0.313448  0.380553  0.134761
H  0.264285  0.317417  0.897220  0.147470 -0.632936

In [106]:
df1.drop("E")

score1    score2    score3    score4    score5    score6
A  0.165853  0.861326  0.749907  0.426012  0.158930 -0.584055
B  0.456251  0.597587  0.540082  0.317487  0.975825 -0.083831
C  0.272142  0.697528  0.620874  0.265688  0.090091 -0.348732
D  0.444873  0.391833  0.248986  0.964221  0.201328  0.195888
F  0.373855  0.082672  0.615873  0.346279  0.740500 -0.242018
G  0.448209  0.020508  0.313448  0.026528  0.380553  0.134761
H  0.264285  0.317417  0.897220  0.552093  0.147470 -0.632936

In [108]:
df2={'ID':[101,102,103,105,107],'Name':['john','mercy','akash','kavin','lally'],'profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  profit
0  101   john      20
1  102  mercy      54
2  103  akash      56
3  105  kavin      87
4  107  lally     123

### assessment

In [109]:
import numpy as np

In [120]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [121]:
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [122]:
b=np.arange(10,65)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64])

In [126]:
b[::-1]

array([64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48,
       47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31,
       30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
       13, 12, 11, 10])

In [124]:
x=np.random.rand(0,8)
y=np.random.rand(0,8)
z=np.random.rand(0,8)


In [125]:
import pandas as pd

In [ ]:
r=pd.Series()